--liquibase formatted sql

--changeset codex:002-create-stock-exchange
CREATE TABLE stock_exchange (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_name VARCHAR(255) NOT NULL,
    exchange_acronym VARCHAR(50) NOT NULL,
    exchange_mic_code VARCHAR(20) NOT NULL,
    polity VARCHAR(100) NOT NULL,
    currency VARCHAR(100) NOT NULL,
    time_zone VARCHAR(100) NOT NULL,
    open_time TIME NOT NULL,
    close_time TIME NOT NULL,
    pre_market_open_time TIME,
    pre_market_close_time TIME,
    post_market_open_time TIME,
    post_market_close_time TIME,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_stock_exchange_mic_code UNIQUE (exchange_mic_code)
);

CREATE INDEX idx_stock_exchange_name ON stock_exchange (exchange_name);
CREATE INDEX idx_stock_exchange_acronym ON stock_exchange (exchange_acronym);
CREATE INDEX idx_stock_exchange_active ON stock_exchange (is_active);
