--liquibase formatted sql

--changeset codex:003-create-stock
CREATE TABLE stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    outstanding_shares BIGINT NOT NULL,
    dividend_yield NUMERIC(19, 4) NOT NULL,
    CONSTRAINT uk_stock_ticker UNIQUE (ticker)
);

CREATE INDEX idx_stock_name ON stock (name);
