--liquibase formatted sql

--changeset codex:004-create-futures-contract
CREATE TABLE futures_contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    contract_size INTEGER NOT NULL,
    contract_unit VARCHAR(32) NOT NULL,
    settlement_date DATE NOT NULL,
    CONSTRAINT uk_futures_contract_ticker UNIQUE (ticker)
);

CREATE INDEX idx_futures_contract_name ON futures_contract (name);
