--liquibase formatted sql

--changeset codex:005-create-forex-pair
CREATE TABLE forex_pair (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(32) NOT NULL,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    exchange_rate NUMERIC(19, 8) NOT NULL,
    liquidity VARCHAR(16) NOT NULL,
    CONSTRAINT uk_forex_pair_ticker UNIQUE (ticker)
);

CREATE INDEX idx_forex_pair_base_quote ON forex_pair (base_currency, quote_currency);
