--liquibase formatted sql

--changeset codex:007-create-listing
CREATE TABLE listing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_id BIGINT NOT NULL,
    listing_type VARCHAR(16) NOT NULL,
    stock_exchange_id BIGINT NOT NULL,
    ticker VARCHAR(64) NOT NULL,
    name VARCHAR(255) NOT NULL,
    last_refresh TIMESTAMP NOT NULL,
    price NUMERIC(19, 8) NOT NULL,
    ask NUMERIC(19, 8) NOT NULL,
    bid NUMERIC(19, 8) NOT NULL,
    volume BIGINT NOT NULL,
    CONSTRAINT fk_listing_stock_exchange
        FOREIGN KEY (stock_exchange_id) REFERENCES stock_exchange (id)
);

CREATE INDEX idx_listing_stock_exchange ON listing (stock_exchange_id);
CREATE INDEX idx_listing_security ON listing (listing_type, security_id);
CREATE INDEX idx_listing_ticker ON listing (ticker);
