--liquibase formatted sql

--changeset codex:023-price-alerts
CREATE TABLE IF NOT EXISTS price_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recipient_type VARCHAR(16) NOT NULL,
    listing_id BIGINT NOT NULL,
    condition VARCHAR(32) NOT NULL,
    threshold NUMERIC(19, 4) NOT NULL,
    notification_type VARCHAR(16) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    last_triggered_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_price_alerts_user_id ON price_alerts (user_id);
CREATE INDEX IF NOT EXISTS idx_price_alerts_active ON price_alerts (active);
