--liquibase formatted sql

--changeset codex:024-watchlists
CREATE TABLE IF NOT EXISTS watchlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_watchlists_user_id ON watchlists (user_id);

CREATE TABLE IF NOT EXISTS watchlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id BIGINT NOT NULL,
    listing_id BIGINT NOT NULL,
    added_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_watchlist_items_watchlist
        FOREIGN KEY (watchlist_id) REFERENCES watchlists (id),
    CONSTRAINT uq_watchlist_items_watchlist_listing
        UNIQUE (watchlist_id, listing_id)
);

CREATE INDEX IF NOT EXISTS idx_watchlist_items_watchlist_id ON watchlist_items (watchlist_id);
