--liquibase formatted sql

--changeset codex:008-create-listing-daily-price-info
CREATE TABLE listing_daily_price_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    date DATE NOT NULL,
    price NUMERIC(19, 8) NOT NULL,
    ask NUMERIC(19, 8) NOT NULL,
    bid NUMERIC(19, 8) NOT NULL,
    change NUMERIC(19, 8) NOT NULL,
    volume BIGINT NOT NULL,
    CONSTRAINT fk_listing_daily_price_info_listing
        FOREIGN KEY (listing_id) REFERENCES listing (id)
);

CREATE INDEX idx_listing_daily_price_info_listing ON listing_daily_price_info (listing_id);
CREATE INDEX idx_listing_daily_price_info_date ON listing_daily_price_info (date);
