// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: banka1/common/v1/types.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForeignBankId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForeignBankId) Reset() {
	*x = ForeignBankId{}
	mi := &file_banka1_common_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForeignBankId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForeignBankId) ProtoMessage() {}

func (x *ForeignBankId) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_common_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForeignBankId.ProtoReflect.Descriptor instead.
func (*ForeignBankId) Descriptor() ([]byte, []int) {
	return file_banka1_common_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ForeignBankId) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *ForeignBankId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IdempotenceKey struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber       int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	LocallyGeneratedKey string                 `protobuf:"bytes,2,opt,name=locally_generated_key,json=locallyGeneratedKey,proto3" json:"locally_generated_key,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IdempotenceKey) Reset() {
	*x = IdempotenceKey{}
	mi := &file_banka1_common_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotenceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotenceKey) ProtoMessage() {}

func (x *IdempotenceKey) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_common_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotenceKey.ProtoReflect.Descriptor instead.
func (*IdempotenceKey) Descriptor() ([]byte, []int) {
	return file_banka1_common_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *IdempotenceKey) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *IdempotenceKey) GetLocallyGeneratedKey() string {
	if x != nil {
		return x.LocallyGeneratedKey
	}
	return ""
}

type MonetaryValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"` // RSD, EUR, USD, CHF, JPY, AUD, CAD, GBP
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`     // BigDecimal serialized as plain string (matches Java WRITE_BIGDECIMAL_AS_PLAIN)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonetaryValue) Reset() {
	*x = MonetaryValue{}
	mi := &file_banka1_common_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonetaryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonetaryValue) ProtoMessage() {}

func (x *MonetaryValue) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_common_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonetaryValue.ProtoReflect.Descriptor instead.
func (*MonetaryValue) Descriptor() ([]byte, []int) {
	return file_banka1_common_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *MonetaryValue) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MonetaryValue) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type StockDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockDescription) Reset() {
	*x = StockDescription{}
	mi := &file_banka1_common_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockDescription) ProtoMessage() {}

func (x *StockDescription) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_common_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockDescription.ProtoReflect.Descriptor instead.
func (*StockDescription) Descriptor() ([]byte, []int) {
	return file_banka1_common_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *StockDescription) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type OptionDescription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NegotiationId  *ForeignBankId         `protobuf:"bytes,1,opt,name=negotiation_id,json=negotiationId,proto3" json:"negotiation_id,omitempty"`
	Stock          *StockDescription      `protobuf:"bytes,2,opt,name=stock,proto3" json:"stock,omitempty"`
	PricePerUnit   *MonetaryValue         `protobuf:"bytes,3,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	SettlementDate string                 `protobuf:"bytes,4,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"` // RFC3339 UTC string (intentionally NOT google.protobuf.Timestamp — Java wire format uses string for OffsetDateTime via Jackson JavaTimeModule)
	Amount         int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OptionDescription) Reset() {
	*x = OptionDescription{}
	mi := &file_banka1_common_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionDescription) ProtoMessage() {}

func (x *OptionDescription) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_common_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionDescription.ProtoReflect.Descriptor instead.
func (*OptionDescription) Descriptor() ([]byte, []int) {
	return file_banka1_common_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *OptionDescription) GetNegotiationId() *ForeignBankId {
	if x != nil {
		return x.NegotiationId
	}
	return nil
}

func (x *OptionDescription) GetStock() *StockDescription {
	if x != nil {
		return x.Stock
	}
	return nil
}

func (x *OptionDescription) GetPricePerUnit() *MonetaryValue {
	if x != nil {
		return x.PricePerUnit
	}
	return nil
}

func (x *OptionDescription) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *OptionDescription) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_banka1_common_v1_types_proto protoreflect.FileDescriptor

const file_banka1_common_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1cbanka1/common/v1/types.proto\x12\x10banka1.common.v1\"F\n" +
	"\rForeignBankId\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"k\n" +
	"\x0eIdempotenceKey\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x122\n" +
	"\x15locally_generated_key\x18\x02 \x01(\tR\x13locallyGeneratedKey\"C\n" +
	"\rMonetaryValue\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"*\n" +
	"\x10StockDescription\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\"\x9d\x02\n" +
	"\x11OptionDescription\x12F\n" +
	"\x0enegotiation_id\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\rnegotiationId\x128\n" +
	"\x05stock\x18\x02 \x01(\v2\".banka1.common.v1.StockDescriptionR\x05stock\x12E\n" +
	"\x0eprice_per_unit\x18\x03 \x01(\v2\x1f.banka1.common.v1.MonetaryValueR\fpricePerUnit\x12'\n" +
	"\x0fsettlement_date\x18\x04 \x01(\tR\x0esettlementDate\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amountBCZAgithub.com/raf-si-2025/banka-1-go/proto/banka1/common/v1;commonv1b\x06proto3"

var (
	file_banka1_common_v1_types_proto_rawDescOnce sync.Once
	file_banka1_common_v1_types_proto_rawDescData []byte
)

func file_banka1_common_v1_types_proto_rawDescGZIP() []byte {
	file_banka1_common_v1_types_proto_rawDescOnce.Do(func() {
		file_banka1_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_banka1_common_v1_types_proto_rawDesc), len(file_banka1_common_v1_types_proto_rawDesc)))
	})
	return file_banka1_common_v1_types_proto_rawDescData
}

var file_banka1_common_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_banka1_common_v1_types_proto_goTypes = []any{
	(*ForeignBankId)(nil),     // 0: banka1.common.v1.ForeignBankId
	(*IdempotenceKey)(nil),    // 1: banka1.common.v1.IdempotenceKey
	(*MonetaryValue)(nil),     // 2: banka1.common.v1.MonetaryValue
	(*StockDescription)(nil),  // 3: banka1.common.v1.StockDescription
	(*OptionDescription)(nil), // 4: banka1.common.v1.OptionDescription
}
var file_banka1_common_v1_types_proto_depIdxs = []int32{
	0, // 0: banka1.common.v1.OptionDescription.negotiation_id:type_name -> banka1.common.v1.ForeignBankId
	3, // 1: banka1.common.v1.OptionDescription.stock:type_name -> banka1.common.v1.StockDescription
	2, // 2: banka1.common.v1.OptionDescription.price_per_unit:type_name -> banka1.common.v1.MonetaryValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_banka1_common_v1_types_proto_init() }
func file_banka1_common_v1_types_proto_init() {
	if File_banka1_common_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_banka1_common_v1_types_proto_rawDesc), len(file_banka1_common_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_banka1_common_v1_types_proto_goTypes,
		DependencyIndexes: file_banka1_common_v1_types_proto_depIdxs,
		MessageInfos:      file_banka1_common_v1_types_proto_msgTypes,
	}.Build()
	File_banka1_common_v1_types_proto = out.File
	file_banka1_common_v1_types_proto_goTypes = nil
	file_banka1_common_v1_types_proto_depIdxs = nil
}
