-- Minimal C3 TODO support tables for Go trading-service.

CREATE TABLE IF NOT EXISTS watchlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uk_watchlists_user_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS watchlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watchlist_id BIGINT NOT NULL REFERENCES watchlists(id),
    ticker VARCHAR(64) NOT NULL,
    listing_type VARCHAR(32) NOT NULL DEFAULT 'STOCK',
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    deleted BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uk_watchlist_items_watchlist_ticker UNIQUE (watchlist_id, ticker)
);

CREATE TABLE IF NOT EXISTS price_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ticker VARCHAR(64) NOT NULL,
    condition VARCHAR(16) NOT NULL,
    threshold NUMERIC(19, 8) NOT NULL,
    notification_type VARCHAR(32) NOT NULL DEFAULT 'EMAIL',
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    triggered_at TIMESTAMP,
    CONSTRAINT chk_price_alert_condition CHECK (condition IN ('ABOVE', 'BELOW'))
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    actor_role VARCHAR(64),
    action_type VARCHAR(80) NOT NULL,
    target_type VARCHAR(80),
    target_id VARCHAR(80),
    old_value TEXT,
    new_value TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recurring_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ticker VARCHAR(64) NOT NULL,
    mode VARCHAR(24) NOT NULL,
    amount NUMERIC(19, 8),
    quantity BIGINT,
    interval VARCHAR(24) NOT NULL,
    account_number VARCHAR(64),
    active BOOLEAN NOT NULL DEFAULT true,
    next_run TIMESTAMP NOT NULL DEFAULT now(),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT chk_recurring_order_mode CHECK (mode IN ('BYAMOUNT', 'BYQUANTITY')),
    CONSTRAINT chk_recurring_order_interval CHECK (interval IN ('DAILY', 'WEEKLY', 'MONTHLY'))
);

CREATE TABLE IF NOT EXISTS dividend_payouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    portfolio_id BIGINT REFERENCES portfolio(id),
    ticker VARCHAR(64) NOT NULL,
    quantity BIGINT NOT NULL,
    price NUMERIC(19, 8) NOT NULL,
    dividend_yield NUMERIC(19, 8) NOT NULL,
    amount NUMERIC(19, 8) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'USD',
    paid_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_watchlists_user ON watchlists(user_id);
CREATE INDEX IF NOT EXISTS idx_price_alerts_user ON price_alerts(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_recurring_orders_user ON recurring_orders(user_id);
CREATE INDEX IF NOT EXISTS idx_dividend_payouts_user ON dividend_payouts(user_id);
