-- Reshape recurring_orders from the C3 stub schema (ticker/interval/amount, no
-- scheduler ever fired it) to the Java order-service schema (013-recurring-
-- orders.sql): listing_id + direction + mode BY_QUANTITY/BY_AMOUNT + "value" +
-- account_id + cadence, with the (active, next_run) due-index the scheduler
-- queries. The stub-shape table is dropped (dev-only data, never executed); a
-- Java-shaped table left by Liquibase is preserved as-is.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'recurring_orders' AND column_name = 'ticker'
    ) THEN
        DROP TABLE recurring_orders;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS recurring_orders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL,
    listing_id  BIGINT         NOT NULL,
    direction   VARCHAR(10)    NOT NULL,
    mode        VARCHAR(20)    NOT NULL,
    -- "value" is quoted to match the Java Liquibase changeset (reserved in H2).
    "value"     NUMERIC(19, 4) NOT NULL,
    account_id  BIGINT         NOT NULL,
    cadence     VARCHAR(20)    NOT NULL,
    next_run    TIMESTAMP      NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_recurring_orders_user_id ON recurring_orders (user_id);
CREATE INDEX IF NOT EXISTS idx_recurring_orders_due ON recurring_orders (active, next_run);
