-- Reshape dividend_payouts from the C3 stub schema (ticker/price/dividend_yield/
-- paid_at — never written to) to the Java trading-service schema (changeset
-- trading-otc/014-dividend-payouts.sql, WP-14 Celina 3.7): one row per dividend
-- payout to one holder for one security. The 15% capital-gains tax is recorded
-- in RSD; for_bank rows are untaxed (Profit Banke). The unique constraint
-- includes for_bank so a holder can have one personal and one bank-held payout
-- per security per day. The stub-shape table is dropped (no data, dev-only); a
-- Java-shaped table left by Liquibase is preserved as-is.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'dividend_payouts' AND column_name = 'paid_at'
    ) THEN
        DROP TABLE dividend_payouts;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS dividend_payouts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT         NOT NULL,
    stock_ticker    VARCHAR(32),
    listing_id      BIGINT         NOT NULL,
    quantity        INT            NOT NULL,
    gross_amount    NUMERIC(19,4)  NOT NULL,
    currency        VARCHAR(8),
    tax_amount_rsd  NUMERIC(19,4)  NOT NULL DEFAULT 0,
    net_amount      NUMERIC(19,4)  NOT NULL,
    account_id      BIGINT,
    payment_date    DATE           NOT NULL,
    for_bank        BOOLEAN        NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_dividend_payout_user_listing_date UNIQUE (user_id, listing_id, payment_date, for_bank)
);

CREATE INDEX IF NOT EXISTS idx_dividend_payouts_user_id ON dividend_payouts (user_id);
CREATE INDEX IF NOT EXISTS idx_dividend_payouts_listing_id ON dividend_payouts (listing_id);
CREATE INDEX IF NOT EXISTS idx_dividend_payouts_payment_date ON dividend_payouts (payment_date DESC);
