-- Reshape audit_log from the C3 stub schema (actor_role/old_value/new_value —
-- nothing ever wrote to it) to the Java trading-service schema (changeset
-- trading-otc/013-audit-log.sql, WP-2 / Issue 9): one row per consumed audit.#
-- event {actorId, actorName, actionType, targetType, targetId, details,
-- createdAt}. The stub-shape table is dropped (dev-only, empty); a Java-shaped
-- table left by Liquibase is preserved as-is.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'audit_log' AND column_name = 'actor_role'
    ) THEN
        DROP TABLE audit_log;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id    BIGINT,
    actor_name  VARCHAR(255),
    action_type VARCHAR(64)  NOT NULL,
    target_type VARCHAR(64),
    target_id   VARCHAR(64),
    details     TEXT,
    created_at  TIMESTAMP    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_action_type ON audit_log (action_type);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor_id ON audit_log (actor_id);
