// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: market/v1/market.proto

package marketv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     int64                  `protobuf:"varint,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingRequest) Reset() {
	*x = GetListingRequest{}
	mi := &file_market_v1_market_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingRequest) ProtoMessage() {}

func (x *GetListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingRequest.ProtoReflect.Descriptor instead.
func (*GetListingRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{0}
}

func (x *GetListingRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

type GetListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   string                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListingResponse) Reset() {
	*x = GetListingResponse{}
	mi := &file_market_v1_market_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListingResponse) ProtoMessage() {}

func (x *GetListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListingResponse.ProtoReflect.Descriptor instead.
func (*GetListingResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{1}
}

func (x *GetListingResponse) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_market_v1_market_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{2}
}

func (x *GetQuoteRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type GetQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   string                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_market_v1_market_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuoteResponse) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

type ConvertRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency      string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency        string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	Amount            string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Date              string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	IncludeCommission bool                   `protobuf:"varint,5,opt,name=include_commission,json=includeCommission,proto3" json:"include_commission,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_market_v1_market_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{4}
}

func (x *ConvertRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ConvertRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ConvertRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ConvertRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ConvertRequest) GetIncludeCommission() bool {
	if x != nil {
		return x.IncludeCommission
	}
	return false
}

type ConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   string                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_market_v1_market_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_v1_market_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_market_v1_market_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertResponse) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

var File_market_v1_market_proto protoreflect.FileDescriptor

const file_market_v1_market_proto_rawDesc = "" +
	"\n" +
	"\x16market/v1/market.proto\x12\tmarket.v1\"2\n" +
	"\x11GetListingRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\x03R\tlistingId\"7\n" +
	"\x12GetListingResponse\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\tR\vjsonPayload\")\n" +
	"\x0fGetQuoteRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\"5\n" +
	"\x10GetQuoteResponse\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\tR\vjsonPayload\"\xb1\x01\n" +
	"\x0eConvertRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\x12-\n" +
	"\x12include_commission\x18\x05 \x01(\bR\x11includeCommission\"4\n" +
	"\x0fConvertResponse\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\tR\vjsonPayload2\xe1\x01\n" +
	"\rMarketService\x12I\n" +
	"\n" +
	"GetListing\x12\x1c.market.v1.GetListingRequest\x1a\x1d.market.v1.GetListingResponse\x12C\n" +
	"\bGetQuote\x12\x1a.market.v1.GetQuoteRequest\x1a\x1b.market.v1.GetQuoteResponse\x12@\n" +
	"\aConvert\x12\x19.market.v1.ConvertRequest\x1a\x1a.market.v1.ConvertResponseB3Z1banka1/market-service-go/proto/market/v1;marketv1b\x06proto3"

var (
	file_market_v1_market_proto_rawDescOnce sync.Once
	file_market_v1_market_proto_rawDescData []byte
)

func file_market_v1_market_proto_rawDescGZIP() []byte {
	file_market_v1_market_proto_rawDescOnce.Do(func() {
		file_market_v1_market_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)))
	})
	return file_market_v1_market_proto_rawDescData
}

var file_market_v1_market_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_market_v1_market_proto_goTypes = []any{
	(*GetListingRequest)(nil),  // 0: market.v1.GetListingRequest
	(*GetListingResponse)(nil), // 1: market.v1.GetListingResponse
	(*GetQuoteRequest)(nil),    // 2: market.v1.GetQuoteRequest
	(*GetQuoteResponse)(nil),   // 3: market.v1.GetQuoteResponse
	(*ConvertRequest)(nil),     // 4: market.v1.ConvertRequest
	(*ConvertResponse)(nil),    // 5: market.v1.ConvertResponse
}
var file_market_v1_market_proto_depIdxs = []int32{
	0, // 0: market.v1.MarketService.GetListing:input_type -> market.v1.GetListingRequest
	2, // 1: market.v1.MarketService.GetQuote:input_type -> market.v1.GetQuoteRequest
	4, // 2: market.v1.MarketService.Convert:input_type -> market.v1.ConvertRequest
	1, // 3: market.v1.MarketService.GetListing:output_type -> market.v1.GetListingResponse
	3, // 4: market.v1.MarketService.GetQuote:output_type -> market.v1.GetQuoteResponse
	5, // 5: market.v1.MarketService.Convert:output_type -> market.v1.ConvertResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_v1_market_proto_init() }
func file_market_v1_market_proto_init() {
	if File_market_v1_market_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_v1_market_proto_rawDesc), len(file_market_v1_market_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_v1_market_proto_goTypes,
		DependencyIndexes: file_market_v1_market_proto_depIdxs,
		MessageInfos:      file_market_v1_market_proto_msgTypes,
	}.Build()
	File_market_v1_market_proto = out.File
	file_market_v1_market_proto_goTypes = nil
	file_market_v1_market_proto_depIdxs = nil
}
