// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: banka1/interbank/v1/interbank.proto

package interbankv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InterbankProtocolService_PostMessage_FullMethodName       = "/banka1.interbank.v1.InterbankProtocolService/PostMessage"
	InterbankProtocolService_CreateNegotiation_FullMethodName = "/banka1.interbank.v1.InterbankProtocolService/CreateNegotiation"
	InterbankProtocolService_PutCounter_FullMethodName        = "/banka1.interbank.v1.InterbankProtocolService/PutCounter"
	InterbankProtocolService_GetNegotiation_FullMethodName    = "/banka1.interbank.v1.InterbankProtocolService/GetNegotiation"
	InterbankProtocolService_DeleteNegotiation_FullMethodName = "/banka1.interbank.v1.InterbankProtocolService/DeleteNegotiation"
	InterbankProtocolService_AcceptNegotiation_FullMethodName = "/banka1.interbank.v1.InterbankProtocolService/AcceptNegotiation"
	InterbankProtocolService_GetPublicStock_FullMethodName    = "/banka1.interbank.v1.InterbankProtocolService/GetPublicStock"
	InterbankProtocolService_GetUserDisplay_FullMethodName    = "/banka1.interbank.v1.InterbankProtocolService/GetUserDisplay"
)

// InterbankProtocolServiceClient is the client API for InterbankProtocolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InterbankProtocolService mirrors the HTTP REST API surface exposed to the partner bank
// (POST /interbank for 2PC, and 7 OTC §3 routes). It is also consumed Go-to-Go by
// other cohort services that need synchronous RPC into the interbank-service.
type InterbankProtocolServiceClient interface {
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error)
	CreateNegotiation(ctx context.Context, in *CreateNegotiationRequest, opts ...grpc.CallOption) (*CreateNegotiationResponse, error)
	PutCounter(ctx context.Context, in *PutCounterRequest, opts ...grpc.CallOption) (*PutCounterResponse, error)
	GetNegotiation(ctx context.Context, in *GetNegotiationRequest, opts ...grpc.CallOption) (*GetNegotiationResponse, error)
	DeleteNegotiation(ctx context.Context, in *DeleteNegotiationRequest, opts ...grpc.CallOption) (*DeleteNegotiationResponse, error)
	AcceptNegotiation(ctx context.Context, in *AcceptNegotiationRequest, opts ...grpc.CallOption) (*AcceptNegotiationResponse, error)
	GetPublicStock(ctx context.Context, in *GetPublicStockRequest, opts ...grpc.CallOption) (*GetPublicStockResponse, error)
	GetUserDisplay(ctx context.Context, in *GetUserDisplayRequest, opts ...grpc.CallOption) (*GetUserDisplayResponse, error)
}

type interbankProtocolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInterbankProtocolServiceClient(cc grpc.ClientConnInterface) InterbankProtocolServiceClient {
	return &interbankProtocolServiceClient{cc}
}

func (c *interbankProtocolServiceClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*PostMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostMessageResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_PostMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interbankProtocolServiceClient) CreateNegotiation(ctx context.Context, in *CreateNegotiationRequest, opts ...grpc.CallOption) (*CreateNegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNegotiationResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_CreateNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interbankProtocolServiceClient) PutCounter(ctx context.Context, in *PutCounterRequest, opts ...grpc.CallOption) (*PutCounterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutCounterResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_PutCounter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interbankProtocolServiceClient) GetNegotiation(ctx context.Context, in *GetNegotiationRequest, opts ...grpc.CallOption) (*GetNegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNegotiationResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_GetNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interbankProtocolServiceClient) DeleteNegotiation(ctx context.Context, in *DeleteNegotiationRequest, opts ...grpc.CallOption) (*DeleteNegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNegotiationResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_DeleteNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interbankProtocolServiceClient) AcceptNegotiation(ctx context.Context, in *AcceptNegotiationRequest, opts ...grpc.CallOption) (*AcceptNegotiationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptNegotiationResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_AcceptNegotiation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interbankProtocolServiceClient) GetPublicStock(ctx context.Context, in *GetPublicStockRequest, opts ...grpc.CallOption) (*GetPublicStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicStockResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_GetPublicStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interbankProtocolServiceClient) GetUserDisplay(ctx context.Context, in *GetUserDisplayRequest, opts ...grpc.CallOption) (*GetUserDisplayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserDisplayResponse)
	err := c.cc.Invoke(ctx, InterbankProtocolService_GetUserDisplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InterbankProtocolServiceServer is the server API for InterbankProtocolService service.
// All implementations should embed UnimplementedInterbankProtocolServiceServer
// for forward compatibility.
//
// InterbankProtocolService mirrors the HTTP REST API surface exposed to the partner bank
// (POST /interbank for 2PC, and 7 OTC §3 routes). It is also consumed Go-to-Go by
// other cohort services that need synchronous RPC into the interbank-service.
type InterbankProtocolServiceServer interface {
	PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error)
	CreateNegotiation(context.Context, *CreateNegotiationRequest) (*CreateNegotiationResponse, error)
	PutCounter(context.Context, *PutCounterRequest) (*PutCounterResponse, error)
	GetNegotiation(context.Context, *GetNegotiationRequest) (*GetNegotiationResponse, error)
	DeleteNegotiation(context.Context, *DeleteNegotiationRequest) (*DeleteNegotiationResponse, error)
	AcceptNegotiation(context.Context, *AcceptNegotiationRequest) (*AcceptNegotiationResponse, error)
	GetPublicStock(context.Context, *GetPublicStockRequest) (*GetPublicStockResponse, error)
	GetUserDisplay(context.Context, *GetUserDisplayRequest) (*GetUserDisplayResponse, error)
}

// UnimplementedInterbankProtocolServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInterbankProtocolServiceServer struct{}

func (UnimplementedInterbankProtocolServiceServer) PostMessage(context.Context, *PostMessageRequest) (*PostMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostMessage not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) CreateNegotiation(context.Context, *CreateNegotiationRequest) (*CreateNegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNegotiation not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) PutCounter(context.Context, *PutCounterRequest) (*PutCounterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutCounter not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) GetNegotiation(context.Context, *GetNegotiationRequest) (*GetNegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNegotiation not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) DeleteNegotiation(context.Context, *DeleteNegotiationRequest) (*DeleteNegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNegotiation not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) AcceptNegotiation(context.Context, *AcceptNegotiationRequest) (*AcceptNegotiationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptNegotiation not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) GetPublicStock(context.Context, *GetPublicStockRequest) (*GetPublicStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicStock not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) GetUserDisplay(context.Context, *GetUserDisplayRequest) (*GetUserDisplayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDisplay not implemented")
}
func (UnimplementedInterbankProtocolServiceServer) testEmbeddedByValue() {}

// UnsafeInterbankProtocolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InterbankProtocolServiceServer will
// result in compilation errors.
type UnsafeInterbankProtocolServiceServer interface {
	mustEmbedUnimplementedInterbankProtocolServiceServer()
}

func RegisterInterbankProtocolServiceServer(s grpc.ServiceRegistrar, srv InterbankProtocolServiceServer) {
	// If the following call panics, it indicates UnimplementedInterbankProtocolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InterbankProtocolService_ServiceDesc, srv)
}

func _InterbankProtocolService_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_PostMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterbankProtocolService_CreateNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).CreateNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_CreateNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).CreateNegotiation(ctx, req.(*CreateNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterbankProtocolService_PutCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutCounterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).PutCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_PutCounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).PutCounter(ctx, req.(*PutCounterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterbankProtocolService_GetNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).GetNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_GetNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).GetNegotiation(ctx, req.(*GetNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterbankProtocolService_DeleteNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).DeleteNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_DeleteNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).DeleteNegotiation(ctx, req.(*DeleteNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterbankProtocolService_AcceptNegotiation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptNegotiationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).AcceptNegotiation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_AcceptNegotiation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).AcceptNegotiation(ctx, req.(*AcceptNegotiationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterbankProtocolService_GetPublicStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).GetPublicStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_GetPublicStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).GetPublicStock(ctx, req.(*GetPublicStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InterbankProtocolService_GetUserDisplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDisplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InterbankProtocolServiceServer).GetUserDisplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InterbankProtocolService_GetUserDisplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InterbankProtocolServiceServer).GetUserDisplay(ctx, req.(*GetUserDisplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InterbankProtocolService_ServiceDesc is the grpc.ServiceDesc for InterbankProtocolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InterbankProtocolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "banka1.interbank.v1.InterbankProtocolService",
	HandlerType: (*InterbankProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostMessage",
			Handler:    _InterbankProtocolService_PostMessage_Handler,
		},
		{
			MethodName: "CreateNegotiation",
			Handler:    _InterbankProtocolService_CreateNegotiation_Handler,
		},
		{
			MethodName: "PutCounter",
			Handler:    _InterbankProtocolService_PutCounter_Handler,
		},
		{
			MethodName: "GetNegotiation",
			Handler:    _InterbankProtocolService_GetNegotiation_Handler,
		},
		{
			MethodName: "DeleteNegotiation",
			Handler:    _InterbankProtocolService_DeleteNegotiation_Handler,
		},
		{
			MethodName: "AcceptNegotiation",
			Handler:    _InterbankProtocolService_AcceptNegotiation_Handler,
		},
		{
			MethodName: "GetPublicStock",
			Handler:    _InterbankProtocolService_GetPublicStock_Handler,
		},
		{
			MethodName: "GetUserDisplay",
			Handler:    _InterbankProtocolService_GetUserDisplay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "banka1/interbank/v1/interbank.proto",
}
