// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: banka1/interbank/v1/interbank.proto

package interbankv1

import (
	v1 "github.com/raf-si-2025/banka-1-go/proto/banka1/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType corresponds to InterbankMessagePayload.messageType on the wire.
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_NEW_TX      MessageType = 1
	MessageType_MESSAGE_TYPE_COMMIT_TX   MessageType = 2
	MessageType_MESSAGE_TYPE_ROLLBACK_TX MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_NEW_TX",
		2: "MESSAGE_TYPE_COMMIT_TX",
		3: "MESSAGE_TYPE_ROLLBACK_TX",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_NEW_TX":      1,
		"MESSAGE_TYPE_COMMIT_TX":   2,
		"MESSAGE_TYPE_ROLLBACK_TX": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_banka1_interbank_v1_interbank_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_banka1_interbank_v1_interbank_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{0}
}

type TransactionVote_Vote int32

const (
	TransactionVote_VOTE_UNSPECIFIED TransactionVote_Vote = 0
	TransactionVote_VOTE_YES         TransactionVote_Vote = 1
	TransactionVote_VOTE_NO          TransactionVote_Vote = 2
)

// Enum value maps for TransactionVote_Vote.
var (
	TransactionVote_Vote_name = map[int32]string{
		0: "VOTE_UNSPECIFIED",
		1: "VOTE_YES",
		2: "VOTE_NO",
	}
	TransactionVote_Vote_value = map[string]int32{
		"VOTE_UNSPECIFIED": 0,
		"VOTE_YES":         1,
		"VOTE_NO":          2,
	}
)

func (x TransactionVote_Vote) Enum() *TransactionVote_Vote {
	p := new(TransactionVote_Vote)
	*p = x
	return p
}

func (x TransactionVote_Vote) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionVote_Vote) Descriptor() protoreflect.EnumDescriptor {
	return file_banka1_interbank_v1_interbank_proto_enumTypes[1].Descriptor()
}

func (TransactionVote_Vote) Type() protoreflect.EnumType {
	return &file_banka1_interbank_v1_interbank_proto_enumTypes[1]
}

func (x TransactionVote_Vote) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionVote_Vote.Descriptor instead.
func (TransactionVote_Vote) EnumDescriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{7, 0}
}

type NoVoteReason_Reason int32

const (
	NoVoteReason_REASON_UNSPECIFIED                  NoVoteReason_Reason = 0
	NoVoteReason_REASON_UNBALANCED_TX                NoVoteReason_Reason = 1
	NoVoteReason_REASON_NO_SUCH_ACCOUNT              NoVoteReason_Reason = 2
	NoVoteReason_REASON_NO_SUCH_ASSET                NoVoteReason_Reason = 3
	NoVoteReason_REASON_UNACCEPTABLE_ASSET           NoVoteReason_Reason = 4
	NoVoteReason_REASON_INSUFFICIENT_ASSET           NoVoteReason_Reason = 5
	NoVoteReason_REASON_OPTION_AMOUNT_INCORRECT      NoVoteReason_Reason = 6
	NoVoteReason_REASON_OPTION_USED_OR_EXPIRED       NoVoteReason_Reason = 7
	NoVoteReason_REASON_OPTION_NEGOTIATION_NOT_FOUND NoVoteReason_Reason = 8
)

// Enum value maps for NoVoteReason_Reason.
var (
	NoVoteReason_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_UNBALANCED_TX",
		2: "REASON_NO_SUCH_ACCOUNT",
		3: "REASON_NO_SUCH_ASSET",
		4: "REASON_UNACCEPTABLE_ASSET",
		5: "REASON_INSUFFICIENT_ASSET",
		6: "REASON_OPTION_AMOUNT_INCORRECT",
		7: "REASON_OPTION_USED_OR_EXPIRED",
		8: "REASON_OPTION_NEGOTIATION_NOT_FOUND",
	}
	NoVoteReason_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":                  0,
		"REASON_UNBALANCED_TX":                1,
		"REASON_NO_SUCH_ACCOUNT":              2,
		"REASON_NO_SUCH_ASSET":                3,
		"REASON_UNACCEPTABLE_ASSET":           4,
		"REASON_INSUFFICIENT_ASSET":           5,
		"REASON_OPTION_AMOUNT_INCORRECT":      6,
		"REASON_OPTION_USED_OR_EXPIRED":       7,
		"REASON_OPTION_NEGOTIATION_NOT_FOUND": 8,
	}
)

func (x NoVoteReason_Reason) Enum() *NoVoteReason_Reason {
	p := new(NoVoteReason_Reason)
	*p = x
	return p
}

func (x NoVoteReason_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoVoteReason_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_banka1_interbank_v1_interbank_proto_enumTypes[2].Descriptor()
}

func (NoVoteReason_Reason) Type() protoreflect.EnumType {
	return &file_banka1_interbank_v1_interbank_proto_enumTypes[2]
}

func (x NoVoteReason_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoVoteReason_Reason.Descriptor instead.
func (NoVoteReason_Reason) EnumDescriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{8, 0}
}

// Asset is the polymorphic asset reference. The Java JSON form is nested
// ({"type":"MONAS","asset":{...}}). The gRPC form uses oneof for the same effect.
type Asset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Asset_Monas
	//	*Asset_Stock
	//	*Asset_Option
	Body          isAsset_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetBody() isAsset_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Asset) GetMonas() *v1.MonetaryValue {
	if x != nil {
		if x, ok := x.Body.(*Asset_Monas); ok {
			return x.Monas
		}
	}
	return nil
}

func (x *Asset) GetStock() *v1.StockDescription {
	if x != nil {
		if x, ok := x.Body.(*Asset_Stock); ok {
			return x.Stock
		}
	}
	return nil
}

func (x *Asset) GetOption() *v1.OptionDescription {
	if x != nil {
		if x, ok := x.Body.(*Asset_Option); ok {
			return x.Option
		}
	}
	return nil
}

type isAsset_Body interface {
	isAsset_Body()
}

type Asset_Monas struct {
	Monas *v1.MonetaryValue `protobuf:"bytes,1,opt,name=monas,proto3,oneof"`
}

type Asset_Stock struct {
	Stock *v1.StockDescription `protobuf:"bytes,2,opt,name=stock,proto3,oneof"`
}

type Asset_Option struct {
	Option *v1.OptionDescription `protobuf:"bytes,3,opt,name=option,proto3,oneof"`
}

func (*Asset_Monas) isAsset_Body() {}

func (*Asset_Stock) isAsset_Body() {}

func (*Asset_Option) isAsset_Body() {}

// TxAccount is the polymorphic account reference.
type TxAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*TxAccount_Person
	//	*TxAccount_AccountNum
	//	*TxAccount_Option
	Body          isTxAccount_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxAccount) Reset() {
	*x = TxAccount{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxAccount) ProtoMessage() {}

func (x *TxAccount) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxAccount.ProtoReflect.Descriptor instead.
func (*TxAccount) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{1}
}

func (x *TxAccount) GetBody() isTxAccount_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TxAccount) GetPerson() *v1.ForeignBankId {
	if x != nil {
		if x, ok := x.Body.(*TxAccount_Person); ok {
			return x.Person
		}
	}
	return nil
}

func (x *TxAccount) GetAccountNum() string {
	if x != nil {
		if x, ok := x.Body.(*TxAccount_AccountNum); ok {
			return x.AccountNum
		}
	}
	return ""
}

func (x *TxAccount) GetOption() *v1.ForeignBankId {
	if x != nil {
		if x, ok := x.Body.(*TxAccount_Option); ok {
			return x.Option
		}
	}
	return nil
}

type isTxAccount_Body interface {
	isTxAccount_Body()
}

type TxAccount_Person struct {
	Person *v1.ForeignBankId `protobuf:"bytes,1,opt,name=person,proto3,oneof"`
}

type TxAccount_AccountNum struct {
	AccountNum string `protobuf:"bytes,2,opt,name=account_num,json=accountNum,proto3,oneof"` // 18-digit account number for type=ACCOUNT
}

type TxAccount_Option struct {
	Option *v1.ForeignBankId `protobuf:"bytes,3,opt,name=option,proto3,oneof"`
}

func (*TxAccount_Person) isTxAccount_Body() {}

func (*TxAccount_AccountNum) isTxAccount_Body() {}

func (*TxAccount_Option) isTxAccount_Body() {}

type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *TxAccount             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // BigDecimal as plain string (matches Java WRITE_BIGDECIMAL_AS_PLAIN)
	Asset         *Asset                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{2}
}

func (x *Posting) GetAccount() *TxAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *Posting) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Posting) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type InterbankTransactionPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransactionId  *v1.ForeignBankId      `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Postings       []*Posting             `protobuf:"bytes,2,rep,name=postings,proto3" json:"postings,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CallNumber     string                 `protobuf:"bytes,4,opt,name=call_number,json=callNumber,proto3" json:"call_number,omitempty"`
	PaymentCode    string                 `protobuf:"bytes,5,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	PaymentPurpose string                 `protobuf:"bytes,6,opt,name=payment_purpose,json=paymentPurpose,proto3" json:"payment_purpose,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterbankTransactionPayload) Reset() {
	*x = InterbankTransactionPayload{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterbankTransactionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterbankTransactionPayload) ProtoMessage() {}

func (x *InterbankTransactionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterbankTransactionPayload.ProtoReflect.Descriptor instead.
func (*InterbankTransactionPayload) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{3}
}

func (x *InterbankTransactionPayload) GetTransactionId() *v1.ForeignBankId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

func (x *InterbankTransactionPayload) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *InterbankTransactionPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InterbankTransactionPayload) GetCallNumber() string {
	if x != nil {
		return x.CallNumber
	}
	return ""
}

func (x *InterbankTransactionPayload) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *InterbankTransactionPayload) GetPaymentPurpose() string {
	if x != nil {
		return x.PaymentPurpose
	}
	return ""
}

type CommitTransactionBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId *v1.ForeignBankId      `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTransactionBody) Reset() {
	*x = CommitTransactionBody{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionBody) ProtoMessage() {}

func (x *CommitTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTransactionBody.ProtoReflect.Descriptor instead.
func (*CommitTransactionBody) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{4}
}

func (x *CommitTransactionBody) GetTransactionId() *v1.ForeignBankId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

type RollbackTransactionBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId *v1.ForeignBankId      `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTransactionBody) Reset() {
	*x = RollbackTransactionBody{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTransactionBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTransactionBody) ProtoMessage() {}

func (x *RollbackTransactionBody) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTransactionBody.ProtoReflect.Descriptor instead.
func (*RollbackTransactionBody) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{5}
}

func (x *RollbackTransactionBody) GetTransactionId() *v1.ForeignBankId {
	if x != nil {
		return x.TransactionId
	}
	return nil
}

type PostMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotenceKey *v1.IdempotenceKey     `protobuf:"bytes,1,opt,name=idempotence_key,json=idempotenceKey,proto3" json:"idempotence_key,omitempty"`
	Type           MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=banka1.interbank.v1.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*PostMessageRequest_NewTx
	//	*PostMessageRequest_CommitTx
	//	*PostMessageRequest_RollbackTx
	Body          isPostMessageRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{6}
}

func (x *PostMessageRequest) GetIdempotenceKey() *v1.IdempotenceKey {
	if x != nil {
		return x.IdempotenceKey
	}
	return nil
}

func (x *PostMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *PostMessageRequest) GetBody() isPostMessageRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *PostMessageRequest) GetNewTx() *InterbankTransactionPayload {
	if x != nil {
		if x, ok := x.Body.(*PostMessageRequest_NewTx); ok {
			return x.NewTx
		}
	}
	return nil
}

func (x *PostMessageRequest) GetCommitTx() *CommitTransactionBody {
	if x != nil {
		if x, ok := x.Body.(*PostMessageRequest_CommitTx); ok {
			return x.CommitTx
		}
	}
	return nil
}

func (x *PostMessageRequest) GetRollbackTx() *RollbackTransactionBody {
	if x != nil {
		if x, ok := x.Body.(*PostMessageRequest_RollbackTx); ok {
			return x.RollbackTx
		}
	}
	return nil
}

type isPostMessageRequest_Body interface {
	isPostMessageRequest_Body()
}

type PostMessageRequest_NewTx struct {
	NewTx *InterbankTransactionPayload `protobuf:"bytes,3,opt,name=new_tx,json=newTx,proto3,oneof"`
}

type PostMessageRequest_CommitTx struct {
	CommitTx *CommitTransactionBody `protobuf:"bytes,4,opt,name=commit_tx,json=commitTx,proto3,oneof"`
}

type PostMessageRequest_RollbackTx struct {
	RollbackTx *RollbackTransactionBody `protobuf:"bytes,5,opt,name=rollback_tx,json=rollbackTx,proto3,oneof"`
}

func (*PostMessageRequest_NewTx) isPostMessageRequest_Body() {}

func (*PostMessageRequest_CommitTx) isPostMessageRequest_Body() {}

func (*PostMessageRequest_RollbackTx) isPostMessageRequest_Body() {}

type TransactionVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          TransactionVote_Vote   `protobuf:"varint,1,opt,name=vote,proto3,enum=banka1.interbank.v1.TransactionVote_Vote" json:"vote,omitempty"`
	Reasons       []*NoVoteReason        `protobuf:"bytes,2,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionVote) Reset() {
	*x = TransactionVote{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionVote) ProtoMessage() {}

func (x *TransactionVote) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionVote.ProtoReflect.Descriptor instead.
func (*TransactionVote) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionVote) GetVote() TransactionVote_Vote {
	if x != nil {
		return x.Vote
	}
	return TransactionVote_VOTE_UNSPECIFIED
}

func (x *TransactionVote) GetReasons() []*NoVoteReason {
	if x != nil {
		return x.Reasons
	}
	return nil
}

type NoVoteReason struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        NoVoteReason_Reason    `protobuf:"varint,1,opt,name=reason,proto3,enum=banka1.interbank.v1.NoVoteReason_Reason" json:"reason,omitempty"`
	Posting       *Posting               `protobuf:"bytes,2,opt,name=posting,proto3" json:"posting,omitempty"` // optional — omitted when reason is global (e.g. UNBALANCED_TX)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoVoteReason) Reset() {
	*x = NoVoteReason{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoVoteReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoVoteReason) ProtoMessage() {}

func (x *NoVoteReason) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoVoteReason.ProtoReflect.Descriptor instead.
func (*NoVoteReason) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{8}
}

func (x *NoVoteReason) GetReason() NoVoteReason_Reason {
	if x != nil {
		return x.Reason
	}
	return NoVoteReason_REASON_UNSPECIFIED
}

func (x *NoVoteReason) GetPosting() *Posting {
	if x != nil {
		return x.Posting
	}
	return nil
}

type PostMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HttpStatusCode int32                  `protobuf:"varint,1,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"` // mirrors HTTP behavior: 200 with body for NEW_TX, 204 for COMMIT/ROLLBACK
	Vote           *TransactionVote       `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote,omitempty"`                                              // populated for NEW_TX only
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostMessageResponse) Reset() {
	*x = PostMessageResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageResponse) ProtoMessage() {}

func (x *PostMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageResponse.ProtoReflect.Descriptor instead.
func (*PostMessageResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{9}
}

func (x *PostMessageResponse) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

func (x *PostMessageResponse) GetVote() *TransactionVote {
	if x != nil {
		return x.Vote
	}
	return nil
}

// OTC §3 message types
type CreateNegotiationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *v1.ForeignBankId      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId          *v1.ForeignBankId      `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId         *v1.ForeignBankId      `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	LastModifiedBy   *v1.ForeignBankId      `protobuf:"bytes,4,opt,name=last_modified_by,json=lastModifiedBy,proto3" json:"last_modified_by,omitempty"`
	StockDescription *v1.StockDescription   `protobuf:"bytes,5,opt,name=stock_description,json=stockDescription,proto3" json:"stock_description,omitempty"`
	PricePerUnit     *v1.MonetaryValue      `protobuf:"bytes,6,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Amount           int32                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	SettlementDate   string                 `protobuf:"bytes,8,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"` // RFC3339 UTC string (Java parity — not Timestamp)
	Premium          *v1.MonetaryValue      `protobuf:"bytes,9,opt,name=premium,proto3" json:"premium,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateNegotiationRequest) Reset() {
	*x = CreateNegotiationRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNegotiationRequest) ProtoMessage() {}

func (x *CreateNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNegotiationRequest.ProtoReflect.Descriptor instead.
func (*CreateNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNegotiationRequest) GetId() *v1.ForeignBankId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateNegotiationRequest) GetBuyerId() *v1.ForeignBankId {
	if x != nil {
		return x.BuyerId
	}
	return nil
}

func (x *CreateNegotiationRequest) GetSellerId() *v1.ForeignBankId {
	if x != nil {
		return x.SellerId
	}
	return nil
}

func (x *CreateNegotiationRequest) GetLastModifiedBy() *v1.ForeignBankId {
	if x != nil {
		return x.LastModifiedBy
	}
	return nil
}

func (x *CreateNegotiationRequest) GetStockDescription() *v1.StockDescription {
	if x != nil {
		return x.StockDescription
	}
	return nil
}

func (x *CreateNegotiationRequest) GetPricePerUnit() *v1.MonetaryValue {
	if x != nil {
		return x.PricePerUnit
	}
	return nil
}

func (x *CreateNegotiationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateNegotiationRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *CreateNegotiationRequest) GetPremium() *v1.MonetaryValue {
	if x != nil {
		return x.Premium
	}
	return nil
}

type CreateNegotiationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.ForeignBankId      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNegotiationResponse) Reset() {
	*x = CreateNegotiationResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNegotiationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNegotiationResponse) ProtoMessage() {}

func (x *CreateNegotiationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNegotiationResponse.ProtoReflect.Descriptor instead.
func (*CreateNegotiationResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{11}
}

func (x *CreateNegotiationResponse) GetId() *v1.ForeignBankId {
	if x != nil {
		return x.Id
	}
	return nil
}

type PutCounterRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber    int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"` // path: /negotiations/{routing_number}/{id}
	Id               string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId          *v1.ForeignBankId      `protobuf:"bytes,3,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId         *v1.ForeignBankId      `protobuf:"bytes,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	LastModifiedBy   *v1.ForeignBankId      `protobuf:"bytes,5,opt,name=last_modified_by,json=lastModifiedBy,proto3" json:"last_modified_by,omitempty"`
	StockDescription *v1.StockDescription   `protobuf:"bytes,6,opt,name=stock_description,json=stockDescription,proto3" json:"stock_description,omitempty"`
	PricePerUnit     *v1.MonetaryValue      `protobuf:"bytes,7,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Amount           int32                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	SettlementDate   string                 `protobuf:"bytes,9,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	Premium          *v1.MonetaryValue      `protobuf:"bytes,10,opt,name=premium,proto3" json:"premium,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PutCounterRequest) Reset() {
	*x = PutCounterRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutCounterRequest) ProtoMessage() {}

func (x *PutCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutCounterRequest.ProtoReflect.Descriptor instead.
func (*PutCounterRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{12}
}

func (x *PutCounterRequest) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *PutCounterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PutCounterRequest) GetBuyerId() *v1.ForeignBankId {
	if x != nil {
		return x.BuyerId
	}
	return nil
}

func (x *PutCounterRequest) GetSellerId() *v1.ForeignBankId {
	if x != nil {
		return x.SellerId
	}
	return nil
}

func (x *PutCounterRequest) GetLastModifiedBy() *v1.ForeignBankId {
	if x != nil {
		return x.LastModifiedBy
	}
	return nil
}

func (x *PutCounterRequest) GetStockDescription() *v1.StockDescription {
	if x != nil {
		return x.StockDescription
	}
	return nil
}

func (x *PutCounterRequest) GetPricePerUnit() *v1.MonetaryValue {
	if x != nil {
		return x.PricePerUnit
	}
	return nil
}

func (x *PutCounterRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PutCounterRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *PutCounterRequest) GetPremium() *v1.MonetaryValue {
	if x != nil {
		return x.Premium
	}
	return nil
}

type PutCounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutCounterResponse) Reset() {
	*x = PutCounterResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutCounterResponse) ProtoMessage() {}

func (x *PutCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutCounterResponse.ProtoReflect.Descriptor instead.
func (*PutCounterResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{13}
}

type GetNegotiationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNegotiationRequest) Reset() {
	*x = GetNegotiationRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNegotiationRequest) ProtoMessage() {}

func (x *GetNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNegotiationRequest.ProtoReflect.Descriptor instead.
func (*GetNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{14}
}

func (x *GetNegotiationRequest) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *GetNegotiationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetNegotiationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Negotiation   *Negotiation           `protobuf:"bytes,1,opt,name=negotiation,proto3" json:"negotiation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNegotiationResponse) Reset() {
	*x = GetNegotiationResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNegotiationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNegotiationResponse) ProtoMessage() {}

func (x *GetNegotiationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNegotiationResponse.ProtoReflect.Descriptor instead.
func (*GetNegotiationResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{15}
}

func (x *GetNegotiationResponse) GetNegotiation() *Negotiation {
	if x != nil {
		return x.Negotiation
	}
	return nil
}

type Negotiation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               *v1.ForeignBankId      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BuyerId          *v1.ForeignBankId      `protobuf:"bytes,2,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	SellerId         *v1.ForeignBankId      `protobuf:"bytes,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	LastModifiedBy   *v1.ForeignBankId      `protobuf:"bytes,4,opt,name=last_modified_by,json=lastModifiedBy,proto3" json:"last_modified_by,omitempty"`
	StockDescription *v1.StockDescription   `protobuf:"bytes,5,opt,name=stock_description,json=stockDescription,proto3" json:"stock_description,omitempty"`
	PricePerUnit     *v1.MonetaryValue      `protobuf:"bytes,6,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Amount           int32                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	SettlementDate   string                 `protobuf:"bytes,8,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	Premium          *v1.MonetaryValue      `protobuf:"bytes,9,opt,name=premium,proto3" json:"premium,omitempty"`
	IsOngoing        bool                   `protobuf:"varint,10,opt,name=is_ongoing,json=isOngoing,proto3" json:"is_ongoing,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Negotiation) Reset() {
	*x = Negotiation{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Negotiation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Negotiation) ProtoMessage() {}

func (x *Negotiation) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Negotiation.ProtoReflect.Descriptor instead.
func (*Negotiation) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{16}
}

func (x *Negotiation) GetId() *v1.ForeignBankId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Negotiation) GetBuyerId() *v1.ForeignBankId {
	if x != nil {
		return x.BuyerId
	}
	return nil
}

func (x *Negotiation) GetSellerId() *v1.ForeignBankId {
	if x != nil {
		return x.SellerId
	}
	return nil
}

func (x *Negotiation) GetLastModifiedBy() *v1.ForeignBankId {
	if x != nil {
		return x.LastModifiedBy
	}
	return nil
}

func (x *Negotiation) GetStockDescription() *v1.StockDescription {
	if x != nil {
		return x.StockDescription
	}
	return nil
}

func (x *Negotiation) GetPricePerUnit() *v1.MonetaryValue {
	if x != nil {
		return x.PricePerUnit
	}
	return nil
}

func (x *Negotiation) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Negotiation) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *Negotiation) GetPremium() *v1.MonetaryValue {
	if x != nil {
		return x.Premium
	}
	return nil
}

func (x *Negotiation) GetIsOngoing() bool {
	if x != nil {
		return x.IsOngoing
	}
	return false
}

type DeleteNegotiationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNegotiationRequest) Reset() {
	*x = DeleteNegotiationRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNegotiationRequest) ProtoMessage() {}

func (x *DeleteNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNegotiationRequest.ProtoReflect.Descriptor instead.
func (*DeleteNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteNegotiationRequest) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *DeleteNegotiationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteNegotiationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNegotiationResponse) Reset() {
	*x = DeleteNegotiationResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNegotiationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNegotiationResponse) ProtoMessage() {}

func (x *DeleteNegotiationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNegotiationResponse.ProtoReflect.Descriptor instead.
func (*DeleteNegotiationResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{18}
}

type AcceptNegotiationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptNegotiationRequest) Reset() {
	*x = AcceptNegotiationRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNegotiationRequest) ProtoMessage() {}

func (x *AcceptNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNegotiationRequest.ProtoReflect.Descriptor instead.
func (*AcceptNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{19}
}

func (x *AcceptNegotiationRequest) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *AcceptNegotiationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AcceptNegotiationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptNegotiationResponse) Reset() {
	*x = AcceptNegotiationResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptNegotiationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNegotiationResponse) ProtoMessage() {}

func (x *AcceptNegotiationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNegotiationResponse.ProtoReflect.Descriptor instead.
func (*AcceptNegotiationResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{20}
}

type GetPublicStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicStockRequest) Reset() {
	*x = GetPublicStockRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicStockRequest) ProtoMessage() {}

func (x *GetPublicStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicStockRequest.ProtoReflect.Descriptor instead.
func (*GetPublicStockRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{21}
}

type GetPublicStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*PublicStockEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicStockResponse) Reset() {
	*x = GetPublicStockResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicStockResponse) ProtoMessage() {}

func (x *GetPublicStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicStockResponse.ProtoReflect.Descriptor instead.
func (*GetPublicStockResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{22}
}

func (x *GetPublicStockResponse) GetEntries() []*PublicStockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PublicStockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Sellers       []*v1.ForeignBankId    `protobuf:"bytes,2,rep,name=sellers,proto3" json:"sellers,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicStockEntry) Reset() {
	*x = PublicStockEntry{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicStockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicStockEntry) ProtoMessage() {}

func (x *PublicStockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicStockEntry.ProtoReflect.Descriptor instead.
func (*PublicStockEntry) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{23}
}

func (x *PublicStockEntry) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *PublicStockEntry) GetSellers() []*v1.ForeignBankId {
	if x != nil {
		return x.Sellers
	}
	return nil
}

func (x *PublicStockEntry) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetUserDisplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDisplayRequest) Reset() {
	*x = GetUserDisplayRequest{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDisplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDisplayRequest) ProtoMessage() {}

func (x *GetUserDisplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDisplayRequest.ProtoReflect.Descriptor instead.
func (*GetUserDisplayRequest) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserDisplayRequest) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *GetUserDisplayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserDisplayResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BankDisplayName string                 `protobuf:"bytes,1,opt,name=bank_display_name,json=bankDisplayName,proto3" json:"bank_display_name,omitempty"`
	DisplayName     string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserDisplayResponse) Reset() {
	*x = GetUserDisplayResponse{}
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDisplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDisplayResponse) ProtoMessage() {}

func (x *GetUserDisplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_banka1_interbank_v1_interbank_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDisplayResponse.ProtoReflect.Descriptor instead.
func (*GetUserDisplayResponse) Descriptor() ([]byte, []int) {
	return file_banka1_interbank_v1_interbank_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserDisplayResponse) GetBankDisplayName() string {
	if x != nil {
		return x.BankDisplayName
	}
	return ""
}

func (x *GetUserDisplayResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_banka1_interbank_v1_interbank_proto protoreflect.FileDescriptor

const file_banka1_interbank_v1_interbank_proto_rawDesc = "" +
	"\n" +
	"#banka1/interbank/v1/interbank.proto\x12\x13banka1.interbank.v1\x1a\x1cbanka1/common/v1/types.proto\"\xc3\x01\n" +
	"\x05Asset\x127\n" +
	"\x05monas\x18\x01 \x01(\v2\x1f.banka1.common.v1.MonetaryValueH\x00R\x05monas\x12:\n" +
	"\x05stock\x18\x02 \x01(\v2\".banka1.common.v1.StockDescriptionH\x00R\x05stock\x12=\n" +
	"\x06option\x18\x03 \x01(\v2#.banka1.common.v1.OptionDescriptionH\x00R\x06optionB\x06\n" +
	"\x04body\"\xac\x01\n" +
	"\tTxAccount\x129\n" +
	"\x06person\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdH\x00R\x06person\x12!\n" +
	"\vaccount_num\x18\x02 \x01(\tH\x00R\n" +
	"accountNum\x129\n" +
	"\x06option\x18\x03 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdH\x00R\x06optionB\x06\n" +
	"\x04body\"\x8d\x01\n" +
	"\aPosting\x128\n" +
	"\aaccount\x18\x01 \x01(\v2\x1e.banka1.interbank.v1.TxAccountR\aaccount\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x120\n" +
	"\x05asset\x18\x03 \x01(\v2\x1a.banka1.interbank.v1.AssetR\x05asset\"\xa6\x02\n" +
	"\x1bInterbankTransactionPayload\x12F\n" +
	"\x0etransaction_id\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\rtransactionId\x128\n" +
	"\bpostings\x18\x02 \x03(\v2\x1c.banka1.interbank.v1.PostingR\bpostings\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vcall_number\x18\x04 \x01(\tR\n" +
	"callNumber\x12!\n" +
	"\fpayment_code\x18\x05 \x01(\tR\vpaymentCode\x12'\n" +
	"\x0fpayment_purpose\x18\x06 \x01(\tR\x0epaymentPurpose\"_\n" +
	"\x15CommitTransactionBody\x12F\n" +
	"\x0etransaction_id\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\rtransactionId\"a\n" +
	"\x17RollbackTransactionBody\x12F\n" +
	"\x0etransaction_id\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\rtransactionId\"\x84\x03\n" +
	"\x12PostMessageRequest\x12I\n" +
	"\x0fidempotence_key\x18\x01 \x01(\v2 .banka1.common.v1.IdempotenceKeyR\x0eidempotenceKey\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .banka1.interbank.v1.MessageTypeR\x04type\x12I\n" +
	"\x06new_tx\x18\x03 \x01(\v20.banka1.interbank.v1.InterbankTransactionPayloadH\x00R\x05newTx\x12I\n" +
	"\tcommit_tx\x18\x04 \x01(\v2*.banka1.interbank.v1.CommitTransactionBodyH\x00R\bcommitTx\x12O\n" +
	"\vrollback_tx\x18\x05 \x01(\v2,.banka1.interbank.v1.RollbackTransactionBodyH\x00R\n" +
	"rollbackTxB\x06\n" +
	"\x04body\"\xc6\x01\n" +
	"\x0fTransactionVote\x12=\n" +
	"\x04vote\x18\x01 \x01(\x0e2).banka1.interbank.v1.TransactionVote.VoteR\x04vote\x12;\n" +
	"\areasons\x18\x02 \x03(\v2!.banka1.interbank.v1.NoVoteReasonR\areasons\"7\n" +
	"\x04Vote\x12\x14\n" +
	"\x10VOTE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bVOTE_YES\x10\x01\x12\v\n" +
	"\aVOTE_NO\x10\x02\"\xa9\x03\n" +
	"\fNoVoteReason\x12@\n" +
	"\x06reason\x18\x01 \x01(\x0e2(.banka1.interbank.v1.NoVoteReason.ReasonR\x06reason\x126\n" +
	"\aposting\x18\x02 \x01(\v2\x1c.banka1.interbank.v1.PostingR\aposting\"\x9e\x02\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REASON_UNBALANCED_TX\x10\x01\x12\x1a\n" +
	"\x16REASON_NO_SUCH_ACCOUNT\x10\x02\x12\x18\n" +
	"\x14REASON_NO_SUCH_ASSET\x10\x03\x12\x1d\n" +
	"\x19REASON_UNACCEPTABLE_ASSET\x10\x04\x12\x1d\n" +
	"\x19REASON_INSUFFICIENT_ASSET\x10\x05\x12\"\n" +
	"\x1eREASON_OPTION_AMOUNT_INCORRECT\x10\x06\x12!\n" +
	"\x1dREASON_OPTION_USED_OR_EXPIRED\x10\a\x12'\n" +
	"#REASON_OPTION_NEGOTIATION_NOT_FOUND\x10\b\"y\n" +
	"\x13PostMessageResponse\x12(\n" +
	"\x10http_status_code\x18\x01 \x01(\x05R\x0ehttpStatusCode\x128\n" +
	"\x04vote\x18\x02 \x01(\v2$.banka1.interbank.v1.TransactionVoteR\x04vote\"\xa4\x04\n" +
	"\x18CreateNegotiationRequest\x12/\n" +
	"\x02id\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\x02id\x12:\n" +
	"\bbuyer_id\x18\x02 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\abuyerId\x12<\n" +
	"\tseller_id\x18\x03 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\bsellerId\x12I\n" +
	"\x10last_modified_by\x18\x04 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\x0elastModifiedBy\x12O\n" +
	"\x11stock_description\x18\x05 \x01(\v2\".banka1.common.v1.StockDescriptionR\x10stockDescription\x12E\n" +
	"\x0eprice_per_unit\x18\x06 \x01(\v2\x1f.banka1.common.v1.MonetaryValueR\fpricePerUnit\x12\x16\n" +
	"\x06amount\x18\a \x01(\x05R\x06amount\x12'\n" +
	"\x0fsettlement_date\x18\b \x01(\tR\x0esettlementDate\x129\n" +
	"\apremium\x18\t \x01(\v2\x1f.banka1.common.v1.MonetaryValueR\apremium\"L\n" +
	"\x19CreateNegotiationResponse\x12/\n" +
	"\x02id\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\x02id\"\xa3\x04\n" +
	"\x11PutCounterRequest\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12:\n" +
	"\bbuyer_id\x18\x03 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\abuyerId\x12<\n" +
	"\tseller_id\x18\x04 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\bsellerId\x12I\n" +
	"\x10last_modified_by\x18\x05 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\x0elastModifiedBy\x12O\n" +
	"\x11stock_description\x18\x06 \x01(\v2\".banka1.common.v1.StockDescriptionR\x10stockDescription\x12E\n" +
	"\x0eprice_per_unit\x18\a \x01(\v2\x1f.banka1.common.v1.MonetaryValueR\fpricePerUnit\x12\x16\n" +
	"\x06amount\x18\b \x01(\x05R\x06amount\x12'\n" +
	"\x0fsettlement_date\x18\t \x01(\tR\x0esettlementDate\x129\n" +
	"\apremium\x18\n" +
	" \x01(\v2\x1f.banka1.common.v1.MonetaryValueR\apremium\"\x14\n" +
	"\x12PutCounterResponse\"N\n" +
	"\x15GetNegotiationRequest\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\\\n" +
	"\x16GetNegotiationResponse\x12B\n" +
	"\vnegotiation\x18\x01 \x01(\v2 .banka1.interbank.v1.NegotiationR\vnegotiation\"\xb6\x04\n" +
	"\vNegotiation\x12/\n" +
	"\x02id\x18\x01 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\x02id\x12:\n" +
	"\bbuyer_id\x18\x02 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\abuyerId\x12<\n" +
	"\tseller_id\x18\x03 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\bsellerId\x12I\n" +
	"\x10last_modified_by\x18\x04 \x01(\v2\x1f.banka1.common.v1.ForeignBankIdR\x0elastModifiedBy\x12O\n" +
	"\x11stock_description\x18\x05 \x01(\v2\".banka1.common.v1.StockDescriptionR\x10stockDescription\x12E\n" +
	"\x0eprice_per_unit\x18\x06 \x01(\v2\x1f.banka1.common.v1.MonetaryValueR\fpricePerUnit\x12\x16\n" +
	"\x06amount\x18\a \x01(\x05R\x06amount\x12'\n" +
	"\x0fsettlement_date\x18\b \x01(\tR\x0esettlementDate\x129\n" +
	"\apremium\x18\t \x01(\v2\x1f.banka1.common.v1.MonetaryValueR\apremium\x12\x1d\n" +
	"\n" +
	"is_ongoing\x18\n" +
	" \x01(\bR\tisOngoing\"Q\n" +
	"\x18DeleteNegotiationRequest\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteNegotiationResponse\"Q\n" +
	"\x18AcceptNegotiationRequest\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x1b\n" +
	"\x19AcceptNegotiationResponse\"\x17\n" +
	"\x15GetPublicStockRequest\"Y\n" +
	"\x16GetPublicStockResponse\x12?\n" +
	"\aentries\x18\x01 \x03(\v2%.banka1.interbank.v1.PublicStockEntryR\aentries\"\x81\x01\n" +
	"\x10PublicStockEntry\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x129\n" +
	"\asellers\x18\x02 \x03(\v2\x1f.banka1.common.v1.ForeignBankIdR\asellers\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"N\n" +
	"\x15GetUserDisplayRequest\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"g\n" +
	"\x16GetUserDisplayResponse\x12*\n" +
	"\x11bank_display_name\x18\x01 \x01(\tR\x0fbankDisplayName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName*~\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_TYPE_NEW_TX\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_COMMIT_TX\x10\x02\x12\x1c\n" +
	"\x18MESSAGE_TYPE_ROLLBACK_TX\x10\x032\xf8\x06\n" +
	"\x18InterbankProtocolService\x12`\n" +
	"\vPostMessage\x12'.banka1.interbank.v1.PostMessageRequest\x1a(.banka1.interbank.v1.PostMessageResponse\x12r\n" +
	"\x11CreateNegotiation\x12-.banka1.interbank.v1.CreateNegotiationRequest\x1a..banka1.interbank.v1.CreateNegotiationResponse\x12]\n" +
	"\n" +
	"PutCounter\x12&.banka1.interbank.v1.PutCounterRequest\x1a'.banka1.interbank.v1.PutCounterResponse\x12i\n" +
	"\x0eGetNegotiation\x12*.banka1.interbank.v1.GetNegotiationRequest\x1a+.banka1.interbank.v1.GetNegotiationResponse\x12r\n" +
	"\x11DeleteNegotiation\x12-.banka1.interbank.v1.DeleteNegotiationRequest\x1a..banka1.interbank.v1.DeleteNegotiationResponse\x12r\n" +
	"\x11AcceptNegotiation\x12-.banka1.interbank.v1.AcceptNegotiationRequest\x1a..banka1.interbank.v1.AcceptNegotiationResponse\x12i\n" +
	"\x0eGetPublicStock\x12*.banka1.interbank.v1.GetPublicStockRequest\x1a+.banka1.interbank.v1.GetPublicStockResponse\x12i\n" +
	"\x0eGetUserDisplay\x12*.banka1.interbank.v1.GetUserDisplayRequest\x1a+.banka1.interbank.v1.GetUserDisplayResponseBIZGgithub.com/raf-si-2025/banka-1-go/proto/banka1/interbank/v1;interbankv1b\x06proto3"

var (
	file_banka1_interbank_v1_interbank_proto_rawDescOnce sync.Once
	file_banka1_interbank_v1_interbank_proto_rawDescData []byte
)

func file_banka1_interbank_v1_interbank_proto_rawDescGZIP() []byte {
	file_banka1_interbank_v1_interbank_proto_rawDescOnce.Do(func() {
		file_banka1_interbank_v1_interbank_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_banka1_interbank_v1_interbank_proto_rawDesc), len(file_banka1_interbank_v1_interbank_proto_rawDesc)))
	})
	return file_banka1_interbank_v1_interbank_proto_rawDescData
}

var file_banka1_interbank_v1_interbank_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_banka1_interbank_v1_interbank_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_banka1_interbank_v1_interbank_proto_goTypes = []any{
	(MessageType)(0),                    // 0: banka1.interbank.v1.MessageType
	(TransactionVote_Vote)(0),           // 1: banka1.interbank.v1.TransactionVote.Vote
	(NoVoteReason_Reason)(0),            // 2: banka1.interbank.v1.NoVoteReason.Reason
	(*Asset)(nil),                       // 3: banka1.interbank.v1.Asset
	(*TxAccount)(nil),                   // 4: banka1.interbank.v1.TxAccount
	(*Posting)(nil),                     // 5: banka1.interbank.v1.Posting
	(*InterbankTransactionPayload)(nil), // 6: banka1.interbank.v1.InterbankTransactionPayload
	(*CommitTransactionBody)(nil),       // 7: banka1.interbank.v1.CommitTransactionBody
	(*RollbackTransactionBody)(nil),     // 8: banka1.interbank.v1.RollbackTransactionBody
	(*PostMessageRequest)(nil),          // 9: banka1.interbank.v1.PostMessageRequest
	(*TransactionVote)(nil),             // 10: banka1.interbank.v1.TransactionVote
	(*NoVoteReason)(nil),                // 11: banka1.interbank.v1.NoVoteReason
	(*PostMessageResponse)(nil),         // 12: banka1.interbank.v1.PostMessageResponse
	(*CreateNegotiationRequest)(nil),    // 13: banka1.interbank.v1.CreateNegotiationRequest
	(*CreateNegotiationResponse)(nil),   // 14: banka1.interbank.v1.CreateNegotiationResponse
	(*PutCounterRequest)(nil),           // 15: banka1.interbank.v1.PutCounterRequest
	(*PutCounterResponse)(nil),          // 16: banka1.interbank.v1.PutCounterResponse
	(*GetNegotiationRequest)(nil),       // 17: banka1.interbank.v1.GetNegotiationRequest
	(*GetNegotiationResponse)(nil),      // 18: banka1.interbank.v1.GetNegotiationResponse
	(*Negotiation)(nil),                 // 19: banka1.interbank.v1.Negotiation
	(*DeleteNegotiationRequest)(nil),    // 20: banka1.interbank.v1.DeleteNegotiationRequest
	(*DeleteNegotiationResponse)(nil),   // 21: banka1.interbank.v1.DeleteNegotiationResponse
	(*AcceptNegotiationRequest)(nil),    // 22: banka1.interbank.v1.AcceptNegotiationRequest
	(*AcceptNegotiationResponse)(nil),   // 23: banka1.interbank.v1.AcceptNegotiationResponse
	(*GetPublicStockRequest)(nil),       // 24: banka1.interbank.v1.GetPublicStockRequest
	(*GetPublicStockResponse)(nil),      // 25: banka1.interbank.v1.GetPublicStockResponse
	(*PublicStockEntry)(nil),            // 26: banka1.interbank.v1.PublicStockEntry
	(*GetUserDisplayRequest)(nil),       // 27: banka1.interbank.v1.GetUserDisplayRequest
	(*GetUserDisplayResponse)(nil),      // 28: banka1.interbank.v1.GetUserDisplayResponse
	(*v1.MonetaryValue)(nil),            // 29: banka1.common.v1.MonetaryValue
	(*v1.StockDescription)(nil),         // 30: banka1.common.v1.StockDescription
	(*v1.OptionDescription)(nil),        // 31: banka1.common.v1.OptionDescription
	(*v1.ForeignBankId)(nil),            // 32: banka1.common.v1.ForeignBankId
	(*v1.IdempotenceKey)(nil),           // 33: banka1.common.v1.IdempotenceKey
}
var file_banka1_interbank_v1_interbank_proto_depIdxs = []int32{
	29, // 0: banka1.interbank.v1.Asset.monas:type_name -> banka1.common.v1.MonetaryValue
	30, // 1: banka1.interbank.v1.Asset.stock:type_name -> banka1.common.v1.StockDescription
	31, // 2: banka1.interbank.v1.Asset.option:type_name -> banka1.common.v1.OptionDescription
	32, // 3: banka1.interbank.v1.TxAccount.person:type_name -> banka1.common.v1.ForeignBankId
	32, // 4: banka1.interbank.v1.TxAccount.option:type_name -> banka1.common.v1.ForeignBankId
	4,  // 5: banka1.interbank.v1.Posting.account:type_name -> banka1.interbank.v1.TxAccount
	3,  // 6: banka1.interbank.v1.Posting.asset:type_name -> banka1.interbank.v1.Asset
	32, // 7: banka1.interbank.v1.InterbankTransactionPayload.transaction_id:type_name -> banka1.common.v1.ForeignBankId
	5,  // 8: banka1.interbank.v1.InterbankTransactionPayload.postings:type_name -> banka1.interbank.v1.Posting
	32, // 9: banka1.interbank.v1.CommitTransactionBody.transaction_id:type_name -> banka1.common.v1.ForeignBankId
	32, // 10: banka1.interbank.v1.RollbackTransactionBody.transaction_id:type_name -> banka1.common.v1.ForeignBankId
	33, // 11: banka1.interbank.v1.PostMessageRequest.idempotence_key:type_name -> banka1.common.v1.IdempotenceKey
	0,  // 12: banka1.interbank.v1.PostMessageRequest.type:type_name -> banka1.interbank.v1.MessageType
	6,  // 13: banka1.interbank.v1.PostMessageRequest.new_tx:type_name -> banka1.interbank.v1.InterbankTransactionPayload
	7,  // 14: banka1.interbank.v1.PostMessageRequest.commit_tx:type_name -> banka1.interbank.v1.CommitTransactionBody
	8,  // 15: banka1.interbank.v1.PostMessageRequest.rollback_tx:type_name -> banka1.interbank.v1.RollbackTransactionBody
	1,  // 16: banka1.interbank.v1.TransactionVote.vote:type_name -> banka1.interbank.v1.TransactionVote.Vote
	11, // 17: banka1.interbank.v1.TransactionVote.reasons:type_name -> banka1.interbank.v1.NoVoteReason
	2,  // 18: banka1.interbank.v1.NoVoteReason.reason:type_name -> banka1.interbank.v1.NoVoteReason.Reason
	5,  // 19: banka1.interbank.v1.NoVoteReason.posting:type_name -> banka1.interbank.v1.Posting
	10, // 20: banka1.interbank.v1.PostMessageResponse.vote:type_name -> banka1.interbank.v1.TransactionVote
	32, // 21: banka1.interbank.v1.CreateNegotiationRequest.id:type_name -> banka1.common.v1.ForeignBankId
	32, // 22: banka1.interbank.v1.CreateNegotiationRequest.buyer_id:type_name -> banka1.common.v1.ForeignBankId
	32, // 23: banka1.interbank.v1.CreateNegotiationRequest.seller_id:type_name -> banka1.common.v1.ForeignBankId
	32, // 24: banka1.interbank.v1.CreateNegotiationRequest.last_modified_by:type_name -> banka1.common.v1.ForeignBankId
	30, // 25: banka1.interbank.v1.CreateNegotiationRequest.stock_description:type_name -> banka1.common.v1.StockDescription
	29, // 26: banka1.interbank.v1.CreateNegotiationRequest.price_per_unit:type_name -> banka1.common.v1.MonetaryValue
	29, // 27: banka1.interbank.v1.CreateNegotiationRequest.premium:type_name -> banka1.common.v1.MonetaryValue
	32, // 28: banka1.interbank.v1.CreateNegotiationResponse.id:type_name -> banka1.common.v1.ForeignBankId
	32, // 29: banka1.interbank.v1.PutCounterRequest.buyer_id:type_name -> banka1.common.v1.ForeignBankId
	32, // 30: banka1.interbank.v1.PutCounterRequest.seller_id:type_name -> banka1.common.v1.ForeignBankId
	32, // 31: banka1.interbank.v1.PutCounterRequest.last_modified_by:type_name -> banka1.common.v1.ForeignBankId
	30, // 32: banka1.interbank.v1.PutCounterRequest.stock_description:type_name -> banka1.common.v1.StockDescription
	29, // 33: banka1.interbank.v1.PutCounterRequest.price_per_unit:type_name -> banka1.common.v1.MonetaryValue
	29, // 34: banka1.interbank.v1.PutCounterRequest.premium:type_name -> banka1.common.v1.MonetaryValue
	19, // 35: banka1.interbank.v1.GetNegotiationResponse.negotiation:type_name -> banka1.interbank.v1.Negotiation
	32, // 36: banka1.interbank.v1.Negotiation.id:type_name -> banka1.common.v1.ForeignBankId
	32, // 37: banka1.interbank.v1.Negotiation.buyer_id:type_name -> banka1.common.v1.ForeignBankId
	32, // 38: banka1.interbank.v1.Negotiation.seller_id:type_name -> banka1.common.v1.ForeignBankId
	32, // 39: banka1.interbank.v1.Negotiation.last_modified_by:type_name -> banka1.common.v1.ForeignBankId
	30, // 40: banka1.interbank.v1.Negotiation.stock_description:type_name -> banka1.common.v1.StockDescription
	29, // 41: banka1.interbank.v1.Negotiation.price_per_unit:type_name -> banka1.common.v1.MonetaryValue
	29, // 42: banka1.interbank.v1.Negotiation.premium:type_name -> banka1.common.v1.MonetaryValue
	26, // 43: banka1.interbank.v1.GetPublicStockResponse.entries:type_name -> banka1.interbank.v1.PublicStockEntry
	32, // 44: banka1.interbank.v1.PublicStockEntry.sellers:type_name -> banka1.common.v1.ForeignBankId
	9,  // 45: banka1.interbank.v1.InterbankProtocolService.PostMessage:input_type -> banka1.interbank.v1.PostMessageRequest
	13, // 46: banka1.interbank.v1.InterbankProtocolService.CreateNegotiation:input_type -> banka1.interbank.v1.CreateNegotiationRequest
	15, // 47: banka1.interbank.v1.InterbankProtocolService.PutCounter:input_type -> banka1.interbank.v1.PutCounterRequest
	17, // 48: banka1.interbank.v1.InterbankProtocolService.GetNegotiation:input_type -> banka1.interbank.v1.GetNegotiationRequest
	20, // 49: banka1.interbank.v1.InterbankProtocolService.DeleteNegotiation:input_type -> banka1.interbank.v1.DeleteNegotiationRequest
	22, // 50: banka1.interbank.v1.InterbankProtocolService.AcceptNegotiation:input_type -> banka1.interbank.v1.AcceptNegotiationRequest
	24, // 51: banka1.interbank.v1.InterbankProtocolService.GetPublicStock:input_type -> banka1.interbank.v1.GetPublicStockRequest
	27, // 52: banka1.interbank.v1.InterbankProtocolService.GetUserDisplay:input_type -> banka1.interbank.v1.GetUserDisplayRequest
	12, // 53: banka1.interbank.v1.InterbankProtocolService.PostMessage:output_type -> banka1.interbank.v1.PostMessageResponse
	14, // 54: banka1.interbank.v1.InterbankProtocolService.CreateNegotiation:output_type -> banka1.interbank.v1.CreateNegotiationResponse
	16, // 55: banka1.interbank.v1.InterbankProtocolService.PutCounter:output_type -> banka1.interbank.v1.PutCounterResponse
	18, // 56: banka1.interbank.v1.InterbankProtocolService.GetNegotiation:output_type -> banka1.interbank.v1.GetNegotiationResponse
	21, // 57: banka1.interbank.v1.InterbankProtocolService.DeleteNegotiation:output_type -> banka1.interbank.v1.DeleteNegotiationResponse
	23, // 58: banka1.interbank.v1.InterbankProtocolService.AcceptNegotiation:output_type -> banka1.interbank.v1.AcceptNegotiationResponse
	25, // 59: banka1.interbank.v1.InterbankProtocolService.GetPublicStock:output_type -> banka1.interbank.v1.GetPublicStockResponse
	28, // 60: banka1.interbank.v1.InterbankProtocolService.GetUserDisplay:output_type -> banka1.interbank.v1.GetUserDisplayResponse
	53, // [53:61] is the sub-list for method output_type
	45, // [45:53] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_banka1_interbank_v1_interbank_proto_init() }
func file_banka1_interbank_v1_interbank_proto_init() {
	if File_banka1_interbank_v1_interbank_proto != nil {
		return
	}
	file_banka1_interbank_v1_interbank_proto_msgTypes[0].OneofWrappers = []any{
		(*Asset_Monas)(nil),
		(*Asset_Stock)(nil),
		(*Asset_Option)(nil),
	}
	file_banka1_interbank_v1_interbank_proto_msgTypes[1].OneofWrappers = []any{
		(*TxAccount_Person)(nil),
		(*TxAccount_AccountNum)(nil),
		(*TxAccount_Option)(nil),
	}
	file_banka1_interbank_v1_interbank_proto_msgTypes[6].OneofWrappers = []any{
		(*PostMessageRequest_NewTx)(nil),
		(*PostMessageRequest_CommitTx)(nil),
		(*PostMessageRequest_RollbackTx)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_banka1_interbank_v1_interbank_proto_rawDesc), len(file_banka1_interbank_v1_interbank_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_banka1_interbank_v1_interbank_proto_goTypes,
		DependencyIndexes: file_banka1_interbank_v1_interbank_proto_depIdxs,
		EnumInfos:         file_banka1_interbank_v1_interbank_proto_enumTypes,
		MessageInfos:      file_banka1_interbank_v1_interbank_proto_msgTypes,
	}.Build()
	File_banka1_interbank_v1_interbank_proto = out.File
	file_banka1_interbank_v1_interbank_proto_goTypes = nil
	file_banka1_interbank_v1_interbank_proto_depIdxs = nil
}
