// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: trading/v1/trading.proto

package tradingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_trading_v1_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_v1_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_trading_v1_trading_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   string                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_trading_v1_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_v1_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_trading_v1_trading_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

type GetLatestAnalyticsRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestAnalyticsRunRequest) Reset() {
	*x = GetLatestAnalyticsRunRequest{}
	mi := &file_trading_v1_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestAnalyticsRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestAnalyticsRunRequest) ProtoMessage() {}

func (x *GetLatestAnalyticsRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trading_v1_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestAnalyticsRunRequest.ProtoReflect.Descriptor instead.
func (*GetLatestAnalyticsRunRequest) Descriptor() ([]byte, []int) {
	return file_trading_v1_trading_proto_rawDescGZIP(), []int{2}
}

type GetLatestAnalyticsRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonPayload   string                 `protobuf:"bytes,1,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestAnalyticsRunResponse) Reset() {
	*x = GetLatestAnalyticsRunResponse{}
	mi := &file_trading_v1_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestAnalyticsRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestAnalyticsRunResponse) ProtoMessage() {}

func (x *GetLatestAnalyticsRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trading_v1_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestAnalyticsRunResponse.ProtoReflect.Descriptor instead.
func (*GetLatestAnalyticsRunResponse) Descriptor() ([]byte, []int) {
	return file_trading_v1_trading_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestAnalyticsRunResponse) GetJsonPayload() string {
	if x != nil {
		return x.JsonPayload
	}
	return ""
}

var File_trading_v1_trading_proto protoreflect.FileDescriptor

const file_trading_v1_trading_proto_rawDesc = "" +
	"\n" +
	"\x18trading/v1/trading.proto\x12\n" +
	"trading.v1\"\r\n" +
	"\vPingRequest\"1\n" +
	"\fPingResponse\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\tR\vjsonPayload\"\x1e\n" +
	"\x1cGetLatestAnalyticsRunRequest\"B\n" +
	"\x1dGetLatestAnalyticsRunResponse\x12!\n" +
	"\fjson_payload\x18\x01 \x01(\tR\vjsonPayload2\xb9\x01\n" +
	"\x0eTradingService\x129\n" +
	"\x04Ping\x12\x17.trading.v1.PingRequest\x1a\x18.trading.v1.PingResponse\x12l\n" +
	"\x15GetLatestAnalyticsRun\x12(.trading.v1.GetLatestAnalyticsRunRequest\x1a).trading.v1.GetLatestAnalyticsRunResponseB6Z4banka1/trading-service-go/proto/trading/v1;tradingv1b\x06proto3"

var (
	file_trading_v1_trading_proto_rawDescOnce sync.Once
	file_trading_v1_trading_proto_rawDescData []byte
)

func file_trading_v1_trading_proto_rawDescGZIP() []byte {
	file_trading_v1_trading_proto_rawDescOnce.Do(func() {
		file_trading_v1_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trading_v1_trading_proto_rawDesc), len(file_trading_v1_trading_proto_rawDesc)))
	})
	return file_trading_v1_trading_proto_rawDescData
}

var file_trading_v1_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_trading_v1_trading_proto_goTypes = []any{
	(*PingRequest)(nil),                   // 0: trading.v1.PingRequest
	(*PingResponse)(nil),                  // 1: trading.v1.PingResponse
	(*GetLatestAnalyticsRunRequest)(nil),  // 2: trading.v1.GetLatestAnalyticsRunRequest
	(*GetLatestAnalyticsRunResponse)(nil), // 3: trading.v1.GetLatestAnalyticsRunResponse
}
var file_trading_v1_trading_proto_depIdxs = []int32{
	0, // 0: trading.v1.TradingService.Ping:input_type -> trading.v1.PingRequest
	2, // 1: trading.v1.TradingService.GetLatestAnalyticsRun:input_type -> trading.v1.GetLatestAnalyticsRunRequest
	1, // 2: trading.v1.TradingService.Ping:output_type -> trading.v1.PingResponse
	3, // 3: trading.v1.TradingService.GetLatestAnalyticsRun:output_type -> trading.v1.GetLatestAnalyticsRunResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trading_v1_trading_proto_init() }
func file_trading_v1_trading_proto_init() {
	if File_trading_v1_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trading_v1_trading_proto_rawDesc), len(file_trading_v1_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trading_v1_trading_proto_goTypes,
		DependencyIndexes: file_trading_v1_trading_proto_depIdxs,
		MessageInfos:      file_trading_v1_trading_proto_msgTypes,
	}.Build()
	File_trading_v1_trading_proto = out.File
	file_trading_v1_trading_proto_goTypes = nil
	file_trading_v1_trading_proto_depIdxs = nil
}
