// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: trading/v1/trading.proto

package tradingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TradingService_Ping_FullMethodName                  = "/trading.v1.TradingService/Ping"
	TradingService_GetLatestAnalyticsRun_FullMethodName = "/trading.v1.TradingService/GetLatestAnalyticsRun"
)

// TradingServiceClient is the client API for TradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TradingService mirrors selected REST reads over gRPC using the same thin
// JSON-payload façade as market-service-go (each RPC returns the JSON string the
// HTTP handler would have produced). gRPC is additive and internal-only; public
// traffic stays HTTP/JSON through the gateway. RPCs are added per phase.
type TradingServiceClient interface {
	// Ping exercises the channel before any domain RPC (returns {"status":"UP"}).
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// GetLatestAnalyticsRun returns the latest COMPLETED analytics run as JSON
	// (same payload as GET /analytics/runs/latest). NOT_FOUND if none exists.
	GetLatestAnalyticsRun(ctx context.Context, in *GetLatestAnalyticsRunRequest, opts ...grpc.CallOption) (*GetLatestAnalyticsRunResponse, error)
}

type tradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTradingServiceClient(cc grpc.ClientConnInterface) TradingServiceClient {
	return &tradingServiceClient{cc}
}

func (c *tradingServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, TradingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) GetLatestAnalyticsRun(ctx context.Context, in *GetLatestAnalyticsRunRequest, opts ...grpc.CallOption) (*GetLatestAnalyticsRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestAnalyticsRunResponse)
	err := c.cc.Invoke(ctx, TradingService_GetLatestAnalyticsRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingServiceServer is the server API for TradingService service.
// All implementations must embed UnimplementedTradingServiceServer
// for forward compatibility.
//
// TradingService mirrors selected REST reads over gRPC using the same thin
// JSON-payload façade as market-service-go (each RPC returns the JSON string the
// HTTP handler would have produced). gRPC is additive and internal-only; public
// traffic stays HTTP/JSON through the gateway. RPCs are added per phase.
type TradingServiceServer interface {
	// Ping exercises the channel before any domain RPC (returns {"status":"UP"}).
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// GetLatestAnalyticsRun returns the latest COMPLETED analytics run as JSON
	// (same payload as GET /analytics/runs/latest). NOT_FOUND if none exists.
	GetLatestAnalyticsRun(context.Context, *GetLatestAnalyticsRunRequest) (*GetLatestAnalyticsRunResponse, error)
	mustEmbedUnimplementedTradingServiceServer()
}

// UnimplementedTradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTradingServiceServer struct{}

func (UnimplementedTradingServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTradingServiceServer) GetLatestAnalyticsRun(context.Context, *GetLatestAnalyticsRunRequest) (*GetLatestAnalyticsRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestAnalyticsRun not implemented")
}
func (UnimplementedTradingServiceServer) mustEmbedUnimplementedTradingServiceServer() {}
func (UnimplementedTradingServiceServer) testEmbeddedByValue()                        {}

// UnsafeTradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradingServiceServer will
// result in compilation errors.
type UnsafeTradingServiceServer interface {
	mustEmbedUnimplementedTradingServiceServer()
}

func RegisterTradingServiceServer(s grpc.ServiceRegistrar, srv TradingServiceServer) {
	// If the following call panics, it indicates UnimplementedTradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TradingService_ServiceDesc, srv)
}

func _TradingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_GetLatestAnalyticsRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestAnalyticsRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).GetLatestAnalyticsRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TradingService_GetLatestAnalyticsRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).GetLatestAnalyticsRun(ctx, req.(*GetLatestAnalyticsRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TradingService_ServiceDesc is the grpc.ServiceDesc for TradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trading.v1.TradingService",
	HandlerType: (*TradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _TradingService_Ping_Handler,
		},
		{
			MethodName: "GetLatestAnalyticsRun",
			Handler:    _TradingService_GetLatestAnalyticsRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trading/v1/trading.proto",
}
